### ISSUE TITLE
推荐我自己

### ISSUE THREAD

**Issue by wujieli0207** [DennisThink/awesome_twitter_CN#4]
厚着脸皮推荐一下我自己 😆，虽然现在粉丝不多，但相信以后会有很多的粉丝

用户名：li_wujie
twitter 地址：https://x.com/li_wujie
领域、关键词：独立开发沉思录

自我介绍：
1. 目前努力向着独立开发、一人公司迈进的程序猿
2. 通过 [“即刻导出”](https://www.wujieli.com/projects/jike-export/) 浏览器插件赚到了独立开发者的第一笔微小收益
3. 目前正在做[独立开发沉思录](https://www.hackthinking.com/)这个网站，每周会发布一篇独立开发沉思录周刊

**Comment by DennisThink** [comment]
好的，我等会把你加入到列表。某种意义上，也是给大家要给交友的机会。

**Comment by DennisThink** [comment]
Finished.

**Comment by DennisThink** [comment]
已经添加到列表。

**Comment by wujieli0207** [comment]
> 已经添加到列表。

感谢感谢

**Comment by DennisThink** [comment]
不客气，你有什么 觉得不错的，也可以推荐。

**Comment by DennisThink** [comment]
wujieli@outlook.com，这是您的邮箱吧，我发了一封邮件拒收了，dennisthink@hotmail.com 这是我的邮箱，方便跟您认识一下吗。

**Comment by wujieli0207** [comment]
> [wujieli@outlook.com](mailto:wujieli@outlook.com)，这是您的邮箱吧，我发了一封邮件拒收了，[dennisthink@hotmail.com](mailto:dennisthink@hotmail.com) 这是我的邮箱，方便跟您认识一下吗。

很高兴认识你，这个是我的邮箱 wujieli0207@outlook.com （网站上忘记更新了 😂）
