### ISSUE TITLE
自荐

### ISSUE THREAD

**Issue by weijunext** [DennisThink/awesome_twitter_CN#5]
用户名 | 领域、关键词 | twitter地址
-- | -- | --
weijunext | 👨‍💻前端🛠️全栈✨AI⛵️出海｜Next.js开源手艺人 | [weijunext](https://x.com/weijunext)

**Comment by DennisThink** [comment]
有觉得不错的也可以推荐哦。

**Comment by DennisThink** [comment]
合并了。
