### ISSUE TITLE
我操！老子上榜了！

### ISSUE THREAD

**Issue by LemonHX** [DennisThink/awesome_twitter_CN#7]
# 我操！老子上榜了！
　　　　　　　　　　　　　　　　　　　　　　　　　　
**　　　　　　　　　　　　　　　　　　　　　　　　　　
　　　　⬛⬛⬛⬛⬛　⬛　　　　⬛　　　⬛⬛⬛⬛⬛　　
　⬛⬛⬛⬛　　⬛⬛　⬛⬛　　　⬛　　　⬛　　　⬛　　
　　　　⬛　　　⬛　　⬛　　⬛⬛⬛　　⬛⬛⬛⬛⬛　　
　　　⬛⬛　　⬛⬛　　　　　　⬛⬛　　　　　　　　　
　⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛　　　⬛　　⬛⬛⬛　⬛⬛⬛　
　　　　⬛　　　⬛　　⬛　　　⬛　　⬛　⬛　⬛　⬛　
　　　　⬛　⬛　⬛　⬛⬛　　　⬛⬛　⬛⬛⬛　⬛⬛⬛　
　⬛⬛⬛⬛⬛　　⬛⬛⬛　　　⬛⬛　　　　　⬛　　　　
　⬛　⬛⬛　　　⬛⬛　　　　　⬛　　⬛⬛⬛⬛⬛⬛⬛⬛
　　　　⬛　　⬛⬛⬛　　⬛　　⬛　　　⬛⬛⬛⬛⬛　　
　　　　⬛　⬛⬛　⬛⬛　⬛　　⬛　　⬛⬛　⬛　⬛⬛　
　　⬛⬛　　　　　　⬛⬛　　⬛⬛　⬛　　　⬛　　　　**

**Comment by DennisThink** [comment]
开不开心？
